Repository milieuinfo/webcomponent-vl-ui-description-data, pull requests merged in 2020-01, with the labels that each got.

#1 Nieuwe testopzet
  .mocharc.js
  README.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  index.js
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
  test/e2e/components/vl-description-data.js
  test/e2e/description-data.test.js
  test/e2e/pages/vl-description-data.page.js
  test/unit/vl-description-data.test.html
  test/wct.docker.conf.json
  wct.docker.conf.json
  wct.local.conf.json
Labels: enhancement

#2 Introductie e2e testen
  demo/demo.css
  demo/demo.css.map
  demo/vl-description-data.html
  package-lock.json
  package.json
  style.css
  style.css.map
  test/e2e/components/vl-description-data.js
  test/e2e/description-data.test.js
  test/e2e/pages/vl-description-data.page.js
  test/unit/vl-description-data.test.html
  vl-description-data.src.js
Labels: chore

#3 Overbodig NPM release import scripts verwijderd
  package.json
Labels: maintenance

#5 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnenDepend op core-branch zonder after
  package.json
Labels: chore

#4 Update vl-ui-util
  package-lock.json
  package.json
  style.css
  test/docker-compose.yml
Labels: maintenance

#6 Update vl-ui-util
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#7 Update vl-ui-util
  bamboo-specs/bamboo.yml
  docker-compose-release.yml
  package-lock.json
  package.json
Labels: maintenance
